name: build

on: [push, pull_request]

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java-version:
          - 11
          - 12
          - 13
          - 14
          - 15

    steps:
      - name: (Temp) Remove Platforms 30
        run: rm -rf $ANDROID_HOME/platforms/android-30

      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - name: Run Tests
        run: ./gradlew check

      - name: Upload Test Failures
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: test-failures
          path: |
            **/build/reports/tests/test/
            **/out/failures/
            paparazzi-gradle-plugin/src/test/projects/**/build/reports/paparazzi/images/

  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs:
      - build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Publish Artifacts
        run: ./gradlew publishMavenPublicationToMavenCentralRepository paparazzi-gradle-plugin:publish
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Prep mkdocs
        run: .github/workflows/prepare_mkdocs.sh

      - name: Build mkdocs
        run: |
          pip3 install -r .github/workflows/requirements.txt
          mkdocs build

      - name: Deploy docs to website
        if: success()
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: site
          CLEAN: true
